### ISSUE TITLE
Is there a way to host a trained model on cpu

### ISSUE THREAD

**Issue by anuragkumar95** [stanford-oval/genienlp#148]
I was wondering if some specific flags need to be set in order to run the model on cpu. Given a trained model, can we host it on CPU? I tried running it in CPU environment, however I get the below error
```
AttributeError: module 'genienlp.models' has no attribute 'Seq2Seq'
```

I trained the model using a GPU and trying to host in a CPU docker container.

**Comment by gcampax** [comment]
I think you have a version incompatibility between the trained model and the serving container. You should make sure that the exact same version of genienlp is used for training and deployment. It looks like you trained a model with genienlp 0.5.0, and are serving with 0.6.0

**Comment by anuragkumar95** [comment]
That worked, but now it returns a different error..
```
05/26/2021 18:53:56 - INFO - genienlp.server -   Loading from /var/shared/model/best.pth
05/26/2021 18:53:56 - INFO - genienlp.models.general_seq2seq -   Loading the model from /var/shared/model/best.pth
05/26/2021 18:53:56 - INFO - genienlp.data_utils.embeddings -   Getting pretrained word vectors and pretrained models
05/26/2021 18:54:03 - INFO - genienlp.data_utils.word_vectors -   Loading vectors from /var/shared/embeddings/glove.840B.300d.txt.vectors.npy
/usr/local/lib/python3.7/site-packages/genienlp/data_utils/word_vectors.py:200: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  self.vectors = torch.from_numpy(vectors)
05/26/2021 18:54:03 - INFO - genienlp.data_utils.word_vectors -   Loading vectors from /var/shared/embeddings/charNgram.txt.vectors.npy
05/26/2021 18:54:03 - INFO - genienlp.models.general_seq2seq -   Loading the accompanying numericalizer from /var/shared/model
05/26/2021 18:54:03 - INFO - genienlp.models.general_seq2seq -   Initializing encoder and decoder embeddings
05/26/2021 18:54:25 - INFO - genienlp.models.general_seq2seq -   Vocabulary has 31299 tokens
Traceback (most recent call last):
  File "/usr/local/bin/genienlp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/genienlp/__main__.py", line 63, in main
    subcommands[argv.subcommand][2](argv)
  File "/usr/local/lib/python3.7/site-packages/genienlp/server.py", line 198, in main
    device=device
  File "/usr/local/lib/python3.7/site-packages/genienlp/models/general_seq2seq.py", line 88, in from_pretrained
    model.load_state_dict(save_dict['model_state_dict'])
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Seq2Seq:
	Missing key(s) in state_dict: "encoder.encoder_embeddings.pretrained_embeddings.0.model.embeddings.position_ids". 
```

**Comment by gcampax** [comment]
I think now you have a version issue with "transformers" (a dependency of genienlp). Probably, when you installed genienlp 0.6.0 you have installed a newer transformers than the one you had for training, and when you downgraded genienlp you did not downgrade transformers. Check all the versions between training and deployment to avoid issues.

**Comment by anuragkumar95** [comment]
```
Collecting mosestokenizer~=1.1
  Downloading mosestokenizer-1.1.0.tar.gz (37 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zqo0g65l/mosestokenizer_17c6ba0403db436e9de2b19fc58549ce/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zqo0g65l/mosestokenizer_17c6ba0403db436e9de2b19fc58549ce/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ds06odpv
         cwd: /tmp/pip-install-zqo0g65l/mosestokenizer_17c6ba0403db436e9de2b19fc58549ce/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zqo0g65l/mosestokenizer_17c6ba0403db436e9de2b19fc58549ce/setup.py", line 28, in <module>
        version=get_version('src', 'mosestokenizer', '__init__.py'),
      File "/tmp/pip-install-zqo0g65l/mosestokenizer_17c6ba0403db436e9de2b19fc58549ce/setup.py", line 18, in get_version
        read(*relpath),
      File "/tmp/pip-install-zqo0g65l/mosestokenizer_17c6ba0403db436e9de2b19fc58549ce/setup.py", line 12, in read
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 83: ordinal not in range(128)
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/4b/b3/c0af235b16c4f44a2828ef017f7947d1262b2646e440f85c6a2ff26a8c6f/mosestokenizer-1.1.0.tar.gz#sha256=27520b3156bc43457ef4272eb8dc40d865e9d0160422e32256ed436df0f00261 (from https://pypi.org/simple/mosestokenizer/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mosestokenizer~=1.1 (from genienlp) (from versions: 0.3.0, 0.5.0, 1.0.0, 1.1.0)
ERROR: No matching distribution found for mosestokenizer~=1.1
The command '/bin/sh -c pip3 install genienlp==0.6.0 pandas numpy tqdm jinja2 pyarango' returned a non-zero code: 1
```
Shouldn't this be handled internally?

**Comment by gcampax** [comment]
This looks like a build problem on your end, while installing a dependency. It might be that you need to enable UTF-8 in your Python install. It has nothing to do with genienlp.

**Comment by Mehrad0711** [comment]
Closing this for now. Please reopen/ open a new issue if there are any other problems.
